### ISSUE TITLE
Connecting to base site without "www." times out

### ISSUE THREAD

**Issue by nate-kean** [is-a-dev/is-a-dev.github.io#1]
[https://​www.is-a.dev/](https://www.is-a.dev/) works as expected, but [h​ttps://is-a.dev/](https://is-a.dev/) (without the "www." at the beginning) never responds and ends up timing out. I bet this has something to do with the unique stuff that is-a.dev does with subdomains.

**Comment by phenax** [comment]
Thanks for letting me know. I think it has something to do with the ssl certificate authenticity as http://is-a.dev works but https://is-a.dev doesn't. Will check it out.

**Comment by phenax** [comment]
This issue has been resolved. Thank you for reporting this!
