### ISSUE TITLE
Suggestion: make is-a.dev be the main url instead of www.is-a.dev

### ISSUE THREAD

**Issue by TheRedXD** [is-a-dev/is-a-dev.github.io#10]
Hey,

So I thought, why not make www.is-a.dev redirect to is-a.dev instead and have is-a.dev be the main page instead? It would make more sense in my eyes as it's a shorter domain, also the service is called is-a.dev

**Comment by wdhdev** [comment]
I think we will keep it on www.is-a.dev as root domains do not support CNAME records.

**Comment by TheRedXD** [comment]
I'm pretty sure they do? I use one for my own website

**Comment by wdhdev** [comment]
They don't in regular DNS, I'm assuming you're using Cloudflare which does support it whereas we use Namecheap.
